### ISSUE TITLE
How to know the default options and parameters?

### ISSUE THREAD

**Issue by Globik** [perry-mitchell/iocane#24] opened 2017-11-28 14:32 UTC
Hi, I am using the method encryptWithPassword and I'm wondering what kind of deafaults are there.  The salt, the iterations, the iv etc? Also I've merked that this method  is slow. Is it encryptWithPassword and decryptWithPassword are using under the skin asynchronous functions?

**Comment by perry-mitchell** [comment] 2017-11-28 18:19
Hi @Globik - A lot of the defaults are in the [constants.js](https://github.com/perry-mitchell/iocane/blob/91f37af4e6e62dedf51fedc03362c8c601ca2fdb/source/constants.js) file. For instance, salts are 12 characters in length, IVs are 16, hashes are sha256, derived keys are sha256 based, HMACs are sha256 based, keys/hmac-keys are 32 bytes (256 bits) and the encryption algo is AES-CBC.

Also, PBKDF2 iterations are randomised per encryption call. They are between 200000 and 250000. This will most likely be why it's "slow", but I can assure you that this is intended and quite common. The slowness is intentional so brute force attacks are made less viable. All functions under the hood are native (NodeJS) and I'm not using any other libraries to perform the encryption. I am using a library to generate the PBKDF2 derived keys, however.

**Comment by Globik** [comment] 2017-11-28 20:24
@perry-mitchell  oh, I see, I see. Thank you for reply. Now I understand.
Any advice about "password"? How long should be the password? Where to keep it? In one's mind?
By the way in readme you didn't provide a catch block to the Promise's functions. I've tested a decryptWithPassword specially with a wrong password and then the nodejs process complains about an uncaught exceptions handler.
Anyway thank you for your great module "iocane.js"!

**Comment by perry-mitchell** [comment] 2017-11-28 20:42
Thanks @Globik.

> you didn't provide a catch block

The catch block should be provided by users of this library. Errors should not be caught in iocane that resulted in an outside issue (ie. wrong password).

There are some edges cases here which I know about, and should get to in a refactoring at some stage.

As for the password - If you're using this to encrypt personal data (such as I do with my password archives), I would keep the password in your head. As for strength? I would do some research yourself to choose what suits you best, but as a completely off-handed suggestion, choose something that is a minimum of 8 characters that has some letters (upper + lower case), numbers and symbols. Something easy to remember but complex at the same time. Also make sure **not** to use this password anywhere else.

**Comment by Globik** [comment] 2017-11-28 21:40
Aha, minimum 8 characters. And not to use anywhere else. Thank you for your reply.

**Comment by Globik** [comment] 2017-11-29 09:32
In component.js line 96 you are resolving the pbkdf2.pbkdf2Sync() function. In their api(pbkdf2) there is also a function pbkdf2() with a callback parameter.
But nodejs doc says that 
Asynchronous system APIs are used by Node.js whenever possible, but where they do not exist, libuv's threadpool is used to create asynchronous node APIs based on synchronous system APIs. Node.js APIs that use the threadpool are:

all fs APIs, other than the file watcher APIs and those that are explicitly synchronous
crypto.pbkdf2()
crypto.randomBytes(), unless it is used without a callback
crypto.randomFill()
I think there is a problem with pdkdf2.js. I think it would be nice if its maintanaiters to refactor their code with a loop operation. Some thing like the lib async.js does : looping through the loop with const limit let's say equal 100...
Update:
No its impossible. Its hardcoded in the native binding to openssl api.

**Comment by Globik** [comment] 2017-11-29 16:00
I can't understand why when decrypting with password the function pbkdf2_def is used?
I have enabled a debug mode and:

  iocane decrypting using password +0ms
  iocane unpacking encrypted content +3ms
  iocane generating derived key using build-in method +8ms
generating derived key using build-in method, rounds:  218503  bits:  512  algo:  sha256 password: secret
  iocane decrypting content +2s
  iocane decrypting using build-in method +1ms
Result of decoding word:  Mother goes shopping
why to generate yet another derived key when decrypting process is running?

**Comment by Globik** [comment] 2017-11-29 16:55
I figured out why. Must compare hash of pwd for authentication.
Is there a method to override constants min/max default derived key iterations?

**Comment by perry-mitchell** [comment] 2017-11-29 17:54
Good comments @Globik - I'll be sure to take these in to account during the refactor. It has been some time since this library was initially written so there will undoubtedly be improvements when I rewrite it. There's [documentation in the readme](https://github.com/perry-mitchell/iocane#overriding-default-pbkdf2-round-bounds) on how to change the default rounds 😊

**Comment by Globik** [comment] 2017-11-29 18:12
Aha, thank you so much. 
Don't you think to write yet another cryptomodule based on crypto API with aes-256-gcm?
I don't know if it safe enough for hackers.

**Comment by perry-mitchell** [comment] 2017-11-29 18:15
You're very welcome!

I originally intended to support GCM, but its support is lacking on many target devices (this library was intended to support some form of cross-platform operation). I'd be happy if you wanted to file a separate issue for that.

I would confidently say that this library is using an extremely secure encryption method (AES-CBC + PBKDF2) for most purposes, but I'm always happy to have options to use different algorithms.

**Comment by perry-mitchell** [comment] 2017-11-29 18:15
I believe the question has been answered, so I'll close this. If you feel that it hasn't I can of course re open it.

**Closed as completed by perry-mitchell** 2017-11-29 18:15 UTC
Labels: question
